package com.example;

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WeatherMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9070918860050700453L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherMessage\",\"fields\":[{\"name\":\"stationId\",\"type\":\"long\"},{\"name\":\"serialNumber\",\"type\":\"long\"},{\"name\":\"batteryStatus\",\"type\":\"string\"},{\"name\":\"statusTimestamp\",\"type\":\"long\"},{\"name\":\"weather\",\"type\":{\"type\":\"record\",\"name\":\"Weather\",\"fields\":[{\"name\":\"humidity\",\"type\":\"int\"},{\"name\":\"temperature\",\"type\":\"int\"},{\"name\":\"windSpeed\",\"type\":\"int\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherMessage> ENCODER =
      new BinaryMessageEncoder<WeatherMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherMessage> DECODER =
      new BinaryMessageDecoder<WeatherMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WeatherMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WeatherMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WeatherMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WeatherMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WeatherMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WeatherMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WeatherMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WeatherMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long stationId;
   private long serialNumber;
   private java.lang.CharSequence batteryStatus;
   private long statusTimestamp;
   private Weather weather;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherMessage() {}

  /**
   * All-args constructor.
   * @param stationId The new value for stationId
   * @param serialNumber The new value for serialNumber
   * @param batteryStatus The new value for batteryStatus
   * @param statusTimestamp The new value for statusTimestamp
   * @param weather The new value for weather
   */
  public WeatherMessage(java.lang.Long stationId, java.lang.Long serialNumber, java.lang.CharSequence batteryStatus, java.lang.Long statusTimestamp, Weather weather) {
    this.stationId = stationId;
    this.serialNumber = serialNumber;
    this.batteryStatus = batteryStatus;
    this.statusTimestamp = statusTimestamp;
    this.weather = weather;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationId;
    case 1: return serialNumber;
    case 2: return batteryStatus;
    case 3: return statusTimestamp;
    case 4: return weather;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationId = (java.lang.Long)value$; break;
    case 1: serialNumber = (java.lang.Long)value$; break;
    case 2: batteryStatus = (java.lang.CharSequence)value$; break;
    case 3: statusTimestamp = (java.lang.Long)value$; break;
    case 4: weather = (Weather)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'stationId' field.
   * @return The value of the 'stationId' field.
   */
  public long getStationId() {
    return stationId;
  }


  /**
   * Sets the value of the 'stationId' field.
   * @param value the value to set.
   */
  public void setStationId(long value) {
    this.stationId = value;
  }

  /**
   * Gets the value of the 'serialNumber' field.
   * @return The value of the 'serialNumber' field.
   */
  public long getSerialNumber() {
    return serialNumber;
  }


  /**
   * Sets the value of the 'serialNumber' field.
   * @param value the value to set.
   */
  public void setSerialNumber(long value) {
    this.serialNumber = value;
  }

  /**
   * Gets the value of the 'batteryStatus' field.
   * @return The value of the 'batteryStatus' field.
   */
  public java.lang.CharSequence getBatteryStatus() {
    return batteryStatus;
  }


  /**
   * Sets the value of the 'batteryStatus' field.
   * @param value the value to set.
   */
  public void setBatteryStatus(java.lang.CharSequence value) {
    this.batteryStatus = value;
  }

  /**
   * Gets the value of the 'statusTimestamp' field.
   * @return The value of the 'statusTimestamp' field.
   */
  public long getStatusTimestamp() {
    return statusTimestamp;
  }


  /**
   * Sets the value of the 'statusTimestamp' field.
   * @param value the value to set.
   */
  public void setStatusTimestamp(long value) {
    this.statusTimestamp = value;
  }

  /**
   * Gets the value of the 'weather' field.
   * @return The value of the 'weather' field.
   */
  public Weather getWeather() {
    return weather;
  }


  /**
   * Sets the value of the 'weather' field.
   * @param value the value to set.
   */
  public void setWeather(Weather value) {
    this.weather = value;
  }

  /**
   * Creates a new WeatherMessage RecordBuilder.
   * @return A new WeatherMessage RecordBuilder
   */
  public static WeatherMessage.Builder newBuilder() {
    return new WeatherMessage.Builder();
  }

  /**
   * Creates a new WeatherMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherMessage RecordBuilder
   */
  public static WeatherMessage.Builder newBuilder(WeatherMessage.Builder other) {
    if (other == null) {
      return new WeatherMessage.Builder();
    } else {
      return new WeatherMessage.Builder(other);
    }
  }

  /**
   * Creates a new WeatherMessage RecordBuilder by copying an existing WeatherMessage instance.
   * @param other The existing instance to copy.
   * @return A new WeatherMessage RecordBuilder
   */
  public static WeatherMessage.Builder newBuilder(WeatherMessage other) {
    if (other == null) {
      return new WeatherMessage.Builder();
    } else {
      return new WeatherMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for WeatherMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherMessage>
    implements org.apache.avro.data.RecordBuilder<WeatherMessage> {

    private long stationId;
    private long serialNumber;
    private java.lang.CharSequence batteryStatus;
    private long statusTimestamp;
    private Weather weather;
    private Weather.Builder weatherBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(WeatherMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.serialNumber)) {
        this.serialNumber = data().deepCopy(fields()[1].schema(), other.serialNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.batteryStatus)) {
        this.batteryStatus = data().deepCopy(fields()[2].schema(), other.batteryStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.statusTimestamp)) {
        this.statusTimestamp = data().deepCopy(fields()[3].schema(), other.statusTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.weather)) {
        this.weather = data().deepCopy(fields()[4].schema(), other.weather);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasWeatherBuilder()) {
        this.weatherBuilder = Weather.newBuilder(other.getWeatherBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(WeatherMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.serialNumber)) {
        this.serialNumber = data().deepCopy(fields()[1].schema(), other.serialNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.batteryStatus)) {
        this.batteryStatus = data().deepCopy(fields()[2].schema(), other.batteryStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.statusTimestamp)) {
        this.statusTimestamp = data().deepCopy(fields()[3].schema(), other.statusTimestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.weather)) {
        this.weather = data().deepCopy(fields()[4].schema(), other.weather);
        fieldSetFlags()[4] = true;
      }
      this.weatherBuilder = null;
    }

    /**
      * Gets the value of the 'stationId' field.
      * @return The value.
      */
    public long getStationId() {
      return stationId;
    }


    /**
      * Sets the value of the 'stationId' field.
      * @param value The value of 'stationId'.
      * @return This builder.
      */
    public WeatherMessage.Builder setStationId(long value) {
      validate(fields()[0], value);
      this.stationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stationId' field has been set.
      * @return True if the 'stationId' field has been set, false otherwise.
      */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stationId' field.
      * @return This builder.
      */
    public WeatherMessage.Builder clearStationId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'serialNumber' field.
      * @return The value.
      */
    public long getSerialNumber() {
      return serialNumber;
    }


    /**
      * Sets the value of the 'serialNumber' field.
      * @param value The value of 'serialNumber'.
      * @return This builder.
      */
    public WeatherMessage.Builder setSerialNumber(long value) {
      validate(fields()[1], value);
      this.serialNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'serialNumber' field has been set.
      * @return True if the 'serialNumber' field has been set, false otherwise.
      */
    public boolean hasSerialNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'serialNumber' field.
      * @return This builder.
      */
    public WeatherMessage.Builder clearSerialNumber() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'batteryStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getBatteryStatus() {
      return batteryStatus;
    }


    /**
      * Sets the value of the 'batteryStatus' field.
      * @param value The value of 'batteryStatus'.
      * @return This builder.
      */
    public WeatherMessage.Builder setBatteryStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.batteryStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'batteryStatus' field has been set.
      * @return True if the 'batteryStatus' field has been set, false otherwise.
      */
    public boolean hasBatteryStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'batteryStatus' field.
      * @return This builder.
      */
    public WeatherMessage.Builder clearBatteryStatus() {
      batteryStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'statusTimestamp' field.
      * @return The value.
      */
    public long getStatusTimestamp() {
      return statusTimestamp;
    }


    /**
      * Sets the value of the 'statusTimestamp' field.
      * @param value The value of 'statusTimestamp'.
      * @return This builder.
      */
    public WeatherMessage.Builder setStatusTimestamp(long value) {
      validate(fields()[3], value);
      this.statusTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'statusTimestamp' field has been set.
      * @return True if the 'statusTimestamp' field has been set, false otherwise.
      */
    public boolean hasStatusTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'statusTimestamp' field.
      * @return This builder.
      */
    public WeatherMessage.Builder clearStatusTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'weather' field.
      * @return The value.
      */
    public Weather getWeather() {
      return weather;
    }


    /**
      * Sets the value of the 'weather' field.
      * @param value The value of 'weather'.
      * @return This builder.
      */
    public WeatherMessage.Builder setWeather(Weather value) {
      validate(fields()[4], value);
      this.weatherBuilder = null;
      this.weather = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'weather' field has been set.
      * @return True if the 'weather' field has been set, false otherwise.
      */
    public boolean hasWeather() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'weather' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public Weather.Builder getWeatherBuilder() {
      if (weatherBuilder == null) {
        if (hasWeather()) {
          setWeatherBuilder(Weather.newBuilder(weather));
        } else {
          setWeatherBuilder(Weather.newBuilder());
        }
      }
      return weatherBuilder;
    }

    /**
     * Sets the Builder instance for the 'weather' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public WeatherMessage.Builder setWeatherBuilder(Weather.Builder value) {
      clearWeather();
      weatherBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'weather' field has an active Builder instance
     * @return True if the 'weather' field has an active Builder instance
     */
    public boolean hasWeatherBuilder() {
      return weatherBuilder != null;
    }

    /**
      * Clears the value of the 'weather' field.
      * @return This builder.
      */
    public WeatherMessage.Builder clearWeather() {
      weather = null;
      weatherBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherMessage build() {
      try {
        WeatherMessage record = new WeatherMessage();
        record.stationId = fieldSetFlags()[0] ? this.stationId : (java.lang.Long) defaultValue(fields()[0]);
        record.serialNumber = fieldSetFlags()[1] ? this.serialNumber : (java.lang.Long) defaultValue(fields()[1]);
        record.batteryStatus = fieldSetFlags()[2] ? this.batteryStatus : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.statusTimestamp = fieldSetFlags()[3] ? this.statusTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        if (weatherBuilder != null) {
          try {
            record.weather = this.weatherBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("weather"));
            throw e;
          }
        } else {
          record.weather = fieldSetFlags()[4] ? this.weather : (Weather) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherMessage>
    READER$ = (org.apache.avro.io.DatumReader<WeatherMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.stationId);

    out.writeLong(this.serialNumber);

    out.writeString(this.batteryStatus);

    out.writeLong(this.statusTimestamp);

    this.weather.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.stationId = in.readLong();

      this.serialNumber = in.readLong();

      this.batteryStatus = in.readString(this.batteryStatus instanceof Utf8 ? (Utf8)this.batteryStatus : null);

      this.statusTimestamp = in.readLong();

      if (this.weather == null) {
        this.weather = new Weather();
      }
      this.weather.customDecode(in);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.stationId = in.readLong();
          break;

        case 1:
          this.serialNumber = in.readLong();
          break;

        case 2:
          this.batteryStatus = in.readString(this.batteryStatus instanceof Utf8 ? (Utf8)this.batteryStatus : null);
          break;

        case 3:
          this.statusTimestamp = in.readLong();
          break;

        case 4:
          if (this.weather == null) {
            this.weather = new Weather();
          }
          this.weather.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










